#!/usr/local/bin/python3
import os
import shutil
_NAME = "devmode"

# [***] _SOURCE and _TARGET were generated by "install.sh"
_SOURCE = "" # // TODO: Sort this out
_TARGET = "" #

class Command:
    prefix = "-"
    inject = prefix + "i"
    launch = prefix + "l"
    remove = prefix + "r"
    save = prefix + "s"
    test = prefix + "t"

class Environment:
    SOURCE_ASSETS = _SOURCE + "/assets"
    SOURCE_COMPONENT = _SOURCE + "/component"
    TARGET_ASSETS = _TARGET + "/assets/" + _NAME
    TARGET_COMPONENT = _TARGET + "/app/components/" + _NAME
    TARGET_HTML = _TARGET + "/app/app.component.html"
    TARGET_MODULE = _TARGET + "/app/app.module.ts"
    
class Injection:
    CLASS_NAME = "DevModeComponent"
    IMPORT_LINE = "import { " + CLASS_NAME + " } from './components/" + _NAME + "/" + _NAME + ".component';"
    CLASS_NAME_LINE = "        " + CLASS_NAME + ","
    HTML_TAG = "    <app-" + _NAME + "></app-" + _NAME + ">"
    MODULE_PREDICATES = ["declarations:", "exports:"]
    HTML_PREDICATE = [""] # TODO: figure out <app-level-html-tag>
    
